In [287]:
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
from sklearn import tree
import pydotplus
import graphviz
from IPython.display import Image
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import ensemble
from sklearn import neighbors
from sklearn import linear_model
import statsmodels.api as sm
%matplotlib inline



In [241]:
df = pd.read_csv('suicide.csv')

In [242]:
df.head()

country  year     sex          age  suicides_no  population  \
0  Albania  1987    male  15-24 years           21      312900   
1  Albania  1987    male  35-54 years           16      308000   
2  Albania  1987  female  15-24 years           14      289700   
3  Albania  1987    male    75+ years            1       21800   
4  Albania  1987    male  25-34 years            9      274300   

   suicides/100k pop country-year  HDI for year  gdp_for_year ($)   \
0               6.71  Albania1987           NaN      2,156,624,900   
1               5.19  Albania1987           NaN      2,156,624,900   
2               4.83  Albania1987           NaN      2,156,624,900   
3               4.59  Albania1987           NaN      2,156,624,900   
4               3.28  Albania1987           NaN      2,156,624,900   

   gdp_per_capita ($)       generation  
0                 796     Generation X  
1                 796           Silent  
2                 796     Generation X  
3                 796  G.I. Generation  
4                 796          Boomers

In [243]:
df_age1 = df[df['age'] == '5-14 years']
df_age2 = df[df['age'] == '15-24 years']
df_age3 = df[df['age'] == '25-34 years']
df_age4 = df[df['age'] == '35-54 years']
df_age5 = df[df['age'] == '55-74 years']
df_age6 = df[df['age'] == '75+ years']




In [244]:
df_age3.head(15)

country  year     sex          age  suicides_no  population  \
4   Albania  1987    male  25-34 years            9      274300   
7   Albania  1987  female  25-34 years            4      257200   
19  Albania  1988  female  25-34 years            5      262400   
20  Albania  1988    male  25-34 years            5      279900   
25  Albania  1989    male  25-34 years           18      283600   
31  Albania  1989  female  25-34 years            2      266300   
39  Albania  1992    male  25-34 years            7      245500   
41  Albania  1992  female  25-34 years            4      267400   
51  Albania  1993    male  25-34 years            9      230100   
54  Albania  1993  female  25-34 years            7      261800   
63  Albania  1994    male  25-34 years            6      231400   
67  Albania  1994  female  25-34 years            4      261100   
72  Albania  1995    male  25-34 years           13      232900   
79  Albania  1995  female  25-34 years            7      264000   
86  Albania  1996    male  25-34 years           14      235300   

    suicides/100k pop country-year  HDI for year  gdp_for_year ($)   \
4                3.28  Albania1987           NaN      2,156,624,900   
7                1.56  Albania1987           NaN      2,156,624,900   
19               1.91  Albania1988           NaN      2,126,000,000   
20               1.79  Albania1988           NaN      2,126,000,000   
25               6.35  Albania1989           NaN      2,335,124,988   
31               0.75  Albania1989           NaN      2,335,124,988   
39               2.85  Albania1992           NaN        709,452,584   
41               1.50  Albania1992           NaN        709,452,584   
51               3.91  Albania1993           NaN      1,228,071,038   
54               2.67  Albania1993           NaN      1,228,071,038   
63               2.59  Albania1994           NaN      1,985,673,798   
67               1.53  Albania1994           NaN      1,985,673,798   
72               5.58  Albania1995         0.619      2,424,499,009   
79               2.65  Albania1995         0.619      2,424,499,009   
86               5.95  Albania1996           NaN      3,314,898,292   

    gdp_per_capita ($)    generation  
4                  796       Boomers  
7                  796       Boomers  
19                 769       Boomers  
20                 769       Boomers  
25                 833       Boomers  
31                 833       Boomers  
39                 251       Boomers  
41                 251       Boomers  
51                 437       Boomers  
54                 437       Boomers  
63                 697       Boomers  
67                 697       Boomers  
72                 835  Generation X  
79                 835  Generation X  
86                1127  Generation X

In [245]:
df_age3.isnull().sum()
df_age3 = df_age3.drop(['HDI for year','year', 'country-year', 'country'], axis=1)
df_age3


sex          age  suicides_no  population  suicides/100k pop  \
4        male  25-34 years            9      274300               3.28   
7      female  25-34 years            4      257200               1.56   
19     female  25-34 years            5      262400               1.91   
20       male  25-34 years            5      279900               1.79   
25       male  25-34 years           18      283600               6.35   
...       ...          ...          ...         ...                ...   
27790  female  25-34 years          148     2556673               5.79   
27797    male  25-34 years          328     2644648              12.40   
27802  female  25-34 years          146     2647820               5.51   
27809    male  25-34 years          318     2739150              11.61   
27814  female  25-34 years          162     2735238               5.92   

       gdp_for_year ($)   gdp_per_capita ($)  generation  
4          2,156,624,900                 796     Boomers  
7          2,156,624,900                 796     Boomers  
19         2,126,000,000                 769     Boomers  
20         2,126,000,000                 769     Boomers  
25         2,335,124,988                 833     Boomers  
...                  ...                 ...         ...  
27790     51,821,573,338                1964  Millenials  
27797     57,690,453,461                2150  Millenials  
27802     57,690,453,461                2150  Millenials  
27809     63,067,077,179                2309  Millenials  
27814     63,067,077,179                2309  Millenials  

[4642 rows x 8 columns]

In [246]:


#df_age3_no_country[' gdp_for_year ($) '] = df_age3_no_country[(df_age3_no_country[' gdp_for_year ($) '].str.replace(',', ''))]
#df_age3_no_country
df_age3

sex          age  suicides_no  population  suicides/100k pop  \
4        male  25-34 years            9      274300               3.28   
7      female  25-34 years            4      257200               1.56   
19     female  25-34 years            5      262400               1.91   
20       male  25-34 years            5      279900               1.79   
25       male  25-34 years           18      283600               6.35   
...       ...          ...          ...         ...                ...   
27790  female  25-34 years          148     2556673               5.79   
27797    male  25-34 years          328     2644648              12.40   
27802  female  25-34 years          146     2647820               5.51   
27809    male  25-34 years          318     2739150              11.61   
27814  female  25-34 years          162     2735238               5.92   

       gdp_for_year ($)   gdp_per_capita ($)  generation  
4          2,156,624,900                 796     Boomers  
7          2,156,624,900                 796     Boomers  
19         2,126,000,000                 769     Boomers  
20         2,126,000,000                 769     Boomers  
25         2,335,124,988                 833     Boomers  
...                  ...                 ...         ...  
27790     51,821,573,338                1964  Millenials  
27797     57,690,453,461                2150  Millenials  
27802     57,690,453,461                2150  Millenials  
27809     63,067,077,179                2309  Millenials  
27814     63,067,077,179                2309  Millenials  

[4642 rows x 8 columns]

In [247]:
#df_age3[' gdp_for_year ($) '] = df_age3[(df_age3[' gdp_for_year ($) '].str.replace(',', ''))]
df_age3[' gdp_for_year ($) '] = df_age3[' gdp_for_year ($) '].str.replace(',', '')
df_age3[' gdp_for_year ($) '] = df_age3[' gdp_for_year ($) '].astype('int64')



In [250]:
df_age3 = pd.get_dummies(df_age3, drop_first=True)
target = df_age3['suicides_no']
df_age3 = df_age3.drop(['suicides_no', 'suicides/100k pop'], axis=1)
X_train,X_test, Y_train, Y_test = train_test_split(df_age3, target, test_size = 0.2)
df_age3.head()

population   gdp_for_year ($)   gdp_per_capita ($)  sex_male  \
4       274300          2156624900                 796         1   
7       257200          2156624900                 796         0   
19      262400          2126000000                 769         0   
20      279900          2126000000                 769         1   
25      283600          2335124988                 833         1   

    generation_Generation X  generation_Millenials  
4                         0                      0  
7                         0                      0  
19                        0                      0  
20                        0                      0  
25                        0                      0

In [253]:
decision_tree = DecisionTreeRegressor(max_depth = 6)

decision_tree.fit(X_train, Y_train)

score = decision_tree.score(X_test, Y_test)
score



0.6297281943455171

In [257]:
cross_val_score(decision_tree, X_test, Y_test, cv = 10)

array([0.20874627, 0.52046949, 0.75617084, 0.51652653, 0.76302374,
       0.89714898, 0.68873711, 0.92080147, 0.96446376, 0.54561347])

In [261]:
rfr = ensemble.RandomForestRegressor(max_depth = 6)
rfr.fit(X_train, Y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=6, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [262]:
rfr.score(X_test, Y_test)

0.6839410074609185

In [264]:
cross_val_score(rfr,X_test,Y_test, cv=10)

array([0.52935782, 0.44536507, 0.90965607, 0.68990127, 0.76260068,
       0.89939922, 0.88832619, 0.90125694, 0.86395479, 0.74985758])

In [277]:
knn = neighbors.KNeighborsRegressor(n_neighbors = 10, weights = 'distance')
knn.fit(X_train, Y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                    weights='distance')

In [278]:
knn.score(X_test, Y_test)


-0.13346609076182103

In [281]:
#cross_val_score(knn, X_test, Y_test, cv=10)
cross_val_score(knn, df_age3, target, cv=10)

array([-13.950208  ,  -0.42906088,  -2.27252157,   0.0670543 ,
        -0.21037278,  -0.21873649,  -2.03289476,  -0.01479339,
        -9.72615985,   0.35382715])

In [291]:
lrm = linear_model.LinearRegression()
lrm.fit(X_train, Y_train)

lrm.score(X_test, Y_test)

0.5509318583949142

In [292]:
X = sm.add_constant(df_age3)

results = sm.OLS(target, X).fit()

results.summary()

/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:            suicides_no   R-squared:                       0.440
Model:                            OLS   Adj. R-squared:                  0.439
Method:                 Least Squares   F-statistic:                     606.9
Date:                Mon, 09 Mar 2020   Prob (F-statistic):               0.00
Time:                        18:52:12   Log-Likelihood:                -36041.
No. Observations:                4642   AIC:                         7.210e+04
Df Residuals:                    4635   BIC:                         7.214e+04
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                    -158.1771     20.275     -7.801      0.000    -197.926    -118.428
population                  0.0001   3.74e-06     36.996      0.000       0.000       0.000
 gdp_for_year ($)        8.623e-12    9.2e-12      0.937      0.349   -9.41e-12    2.67e-11
gdp_per_capita ($)      -5.259e-05      0.000     -0.105      0.916      -0.001       0.001
sex_male                  300.8885     16.736     17.979      0.000     268.078     333.699
generation_Generation X     2.4793     20.380      0.122      0.903     -37.475      42.434
generation_Millenials     -36.5307     27.383     -1.334      0.182     -90.213      17.152
==============================================================================
Omnibus:                     6177.597   Durbin-Watson:                   2.235
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1564718.137
Skew:                           7.450   Prob(JB):                         0.00
Kurtosis:                      91.701   Cond. No.                     6.08e+12
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.08e+12. This might indicate that there are
strong multicollinearity or other numerical problems.
"""